### ISSUE TITLE
Can't set snackbar duration

### ISSUE THREAD

**Issue by jsp-up** [kalidea/kaligraphi#107]
We can't set the duration of the snackbar.
`duration: 100000` will still close the snackbar after 5 seconds.

**Comment by ydomenjoud** [comment]
Please provide code you used .

**Comment by jsp-up** [comment]
`const config = new KalSnackbarConfig({
        title: 'Impossible d\'ouvrir le document : celui-ci n\'est pas encore enregistré.',
        duration: 10
      });

      this.snackbarService.open(config);
`

**Comment by ydomenjoud** [comment]
fixed
