### ISSUE TITLE
Linear mode not working

### ISSUE THREAD

**Issue by jsp-up** [kalidea/kaligraphi#127]
Enabling linear mode on KalStepper still allow the user to click on steps which shouldn't be allowed.

**Comment by ydomenjoud** [comment]
Please provide a rzpo

**Comment by ydomenjoud** [comment]
Provide sample. Does playground works ?

**Comment by jsp-up** [comment]
No it doesn't works.
Sample : (https://stackblitz.com/edit/angular-rpueps)

**Comment by ydomenjoud** [comment]
you must use formControl to control steps
