### ISSUE TITLE
KalOption bug

### ISSUE THREAD

**Issue by jsp-up** [kalidea/kaligraphi#167]
If we pass a new set of options the KalMenu won't close.

Example : [https://stackblitz.com/edit/angular-2g7nrw?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-2g7nrw?file=src%2Fapp%2Fapp.component.ts)

**Comment by ydomenjoud** [comment]
clarification: kalMenu won't close on Option click
